### ISSUE TITLE
[Feature request] Language dependent commands

### ISSUE THREAD

**Issue by Hutch79** [tritonmc/Triton#198]
## The Idea

Triton can already send different messages for different languages, so why should the same thing not also be possible for commands?

## Possible implementation
Language dependent commands could be executed with `/triton command [set_your_command_name] <player>`.
It would add a new config file or even a folder where multiple files with commands could be in.

### Config structure
To configure the commands, it would not be necessary to integrate this in twin, although it would be very nice! ;-)
I thought about a very simple yml file structure like:
```
command_name: # The key to execute it. (/triton command command_name)
  as-player: false # True: execute as the Player, False, Execute as console
  as-player-op: false # True: Executa as if the player is op, False: Execute with current player permission
  command:
    de_ch: '/your cool command for swiss people'
    en_GB: '/your cool command for british people'
    de_DE:
      - '/your first command for german people'
      - '/your seccond command for german people'
```

### Command syntax
`/triton command [key] <player>`
The `[key]` is the name of the command which is stored in the yml file.
`<player>` is an optional argument, where you can set a player as executor. Like the vanilla `/execute as <player>`. If not provided, it takes the sender of the command.

## Use case
I would use it for playing the right audio language for a player.
I want to create Quests where you can listen to the NPC's talking and not only read the conversation.
Therefore, I need a way to play the correct audio file for the players language

Another use case would be to translate resource packs.
You would need a second plugin for this, that can send different resource packs depending on which command you have executed.
You could then force every player to execute `/triton command pack` and depending on the selected language, it would send a different texture pack.
