### ISSUE TITLE
ITEM_FRAME Hover can't detect

### ISSUE THREAD

**Issue by OverBrave** [tritonmc/Triton#201]
![image](https://user-images.githubusercontent.com/47111280/174591236-f15d277d-c3e4-4ee3-8ed4-a98f6dfd78fb.png)

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.18.2
 - Client Minecraft Version: 1.18.2
 - Velocity
 - Triton Version: 3.7.4

```
  holograms:
    # Should the plugin check for placeholders in holograms (and/or entity display names)?
    # Normally the most recent plugins use armor stands to make the holograms, but if they don't, you can change it here.
    # Also, you can also translate other's entities name, like villagers. Add their entity type on the list below.
    # Full list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    types:
      - ARMOR_STAND
      - ITEM_FRAME
    # When enabled, the list above is ignored and all entities' names are checked and translated.
    allow-all: true
    syntax-lang: lang
    syntax-args: args
    syntax-arg: arg
```
