### ISSUE TITLE
1.20 `ITEM_DISPLAY` not supported

### ISSUE THREAD

**Issue by SleepyAsh0191** [tritonmc/Triton#322]
```
[16:02:47 WARN]: [Triton] Failed to register hologram type TEXT_DISPLAY because it's not a valid entity type! Please check your spelling and if you can't fix it, please contact the developer!
```

 Once i set entity type in config, It appear this warning in console

 ```yml
  holograms:
    # Should the plugin check for placeholders in holograms (and/or entity display names)?
    # Normally the most recent plugins use armor stands to make the holograms, but if they don't, you can change it here.
    # Also, you can also translate other's entities name, like villagers. Add their entity type on the list below.
    # Full list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    types:
      - ARMOR_STAND
      - TEXT_DISPLAY
  ```

In the latest version of CMI, holograms usually uses TEXT_DISPLAY for show texts(too lazy to set back to legacy type)
