### ISSUE TITLE
Nova compatibility

### ISSUE THREAD

**Issue by SleepyAsh0191** [tritonmc/Triton#323]
### Describe the bug

Once I enable bossbar check in `config.yml`
```yml
  bossbars:
    # Should the plugin check for placeholders in bossbars? (1.9+)
    enabled: true
```
reload
the bossbar in game will appear like this
![image](https://github.com/tritonmc/Triton/assets/64446140/8771323a-df6b-4608-9d66-7ee265f53f4a)

when I disable bossbar check and reload
![image](https://github.com/tritonmc/Triton/assets/64446140/da3c98d2-54fe-4685-800a-46ac13a0731a)

Tips: Nova replaced bossbar texture to empty and hooked text (use font feature)

### How can the bug be reproduced?

1. Install [Nova](https://github.com/xenondevs/Nova)
2. Apply nova resourcepacks
3. Install Triton and enable it
4. Send a bossbar message

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-paper-169

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.20.1

### What's the Triton version you're using?

3.9.0
